[build]
  # Build command for Next.js static export
  command = "npm run build"
  
  # Directory to publish (Next.js static export output)
  publish = "out"
  
  # Node.js version to use for builds
  # Using Node.js 18 for better compatibility with Next.js 13.5.1
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Ensure npm ci is used for faster, more reliable builds
  NPM_FLAGS = "--production=false"

# Handle client-side routing for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Security headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle API routes if any (though this app uses client-side Supabase)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Prevent indexing of admin or sensitive pages
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"